name: CI/CD Workflow

on:
  push:
    paths:
      - 'Service1/**'
  workflow_dispatch:
    inputs:
      Services:
          description: 'Service'
          required: true
          default: 'Service1'
          type: choice
          options:
          - Service1
          - Service2
          - Service3
jobs:
  build:
    name: Build in Development
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' && github.event.inputs.Services == 'Service1' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build
      run: |
        echo "Building the project"

  test-dev:
    name: Test in Development
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' && github.event.inputs.Services == 'Service1' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test
      run: |
        echo "Running tests in Development environment..."
        
  deploy-dev:
    name: Deploy in Development
    runs-on: ubuntu-latest
    needs: test-dev
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' && github.event.inputs.Services == 'Service1' }}
    environment: Service1-dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy
      run: |
        echo "Deploying to Development environment..."
        

  test-prod:
    name: Test in Production
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.Services == 'Service1' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test
      run: |
        echo "Running tests in Production environment..."
       

  deploy-prod:
    name: Deploy in Production
    runs-on: ubuntu-latest
    needs: test-prod
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.Services == 'Service1' }}
    environment: Service1-prod

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy
      run: |
        echo "Deploying to Production environment..."
